- hosts: maven
  remote_user: ec2-user
  become: yes
  tasks:
    - name: yum update
      yum: 
        name: "*"
        state: present
    - name: java install
      yum: 
        name: java-1.8.0-openjdk
        state: present   

    - name: Download tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.53/bin/apache-tomcat-9.0.53.tar.gz
        dest: /usr/local
        mode: '0777'
    - unarchive:
        src: /usr/local/apache-tomcat-9.0.53.tar.gz
        dest: /usr/local
        remote_src: True
        mode: '0777'
        
    - name: start tomcat
      shell: nohup /usr/local/apache-tomcat-9.0.53/bin/startup.sh &
    - name: Create a zip archive of /path/to/foo
      archive:
        path: ./build
        dest: /usr/local/apache-tomcat-9.0.53/webapps/
        format: zip
